### ISSUE TITLE
Issue on loading redis stats

### ISSUE THREAD

**Issue by zahraamumtaz** [Deadly0/bull-board-docker#21]
I have configured this in my docker-compose.yml file but my redis stats are not loading and the screen is blank. Adding configuration and screenhots for referance.

```
bull-board:
    container_name: bullboard
    image: deadly0/bull-board
    restart: always
    ports:
      - 8000:3000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 96104305cdf1e02badc378cef3f60f23319d1600a6de13f71f120e476061dba3
      REDIS_USE_TLS: 'false'
      BULL_PREFIX: bull
    depends_on:
      - redis
```

      
<img width="1268" alt="Screenshot 2023-09-06 at 4 40 01 PM" src="https://github.com/Deadly0/bull-board-docker/assets/97101282/cd88e656-1ca4-4646-a53e-713eaabd3850">

<img width="1501" alt="Screenshot 2023-09-06 at 4 38 58 PM" src="https://github.com/Deadly0/bull-board-docker/assets/97101282/c3b09ef1-aa47-4b53-9899-6adc4943e15b">
