### ISSUE TITLE
Queues detected but jobs not listed

### ISSUE THREAD

**Issue by MeStrak** [Deadly0/bull-board-docker#4]
Hi, I'm trying to run bull-board from the docker image but have a problem that no jobs are shown, even though the queues are detected.

I originally created this issue in the bull-board repo (https://github.com/felixmosh/bull-board/issues/249) but they analysed it and don't think it is related directly to bull-board.

I have started up the container, and my bull queues are detected:

![image](https://user-images.githubusercontent.com/31989238/114317572-02dd4a80-9b09-11eb-86b4-25e88377c668.png)

However, no jobs ever show in the UI. Running `.backgroundDataQueue.getJobCounts()` gives the following:

```
{
  waiting: 1,
  active: 0,
  completed: 25,
  failed: 0,
  delayed: 5,
  paused: 0
}
```

But all job categories in the UI are empty. For example:
![image](https://user-images.githubusercontent.com/31989238/114317743-d544d100-9b09-11eb-889d-9323d5680e5f.png)

![image](https://user-images.githubusercontent.com/31989238/114317757-e68ddd80-9b09-11eb-8d36-e9dacbe39f11.png)

Is there some additional config that I need to do to detect the jobs? Or should it work automatically if the queues are detected?

Thanks!

**Comment by Deadly0** [comment]
@MeStrak hi, did you try to run bull-board directly (without this docker image)?
Do you use bull or bullmq?
Can you share settings (env vars) witch you use to run container?

**Comment by SloCompTech** [comment]
I have the same issues, here is my part of docker-compose:

```
bull-ui:
    image: deadly0/bull-board:3.2.6
    container_name: queue-qui
    depends_on:
      - redis
    restart: unless-stopped
    ports:
      - 8082:3000
    environment:
      REDIS_HOST: 'q-redis'
      REDIS_PORT: 6379
      REDIS_USE_TLS: 'false'
      BULL_PREFIX: 'queue'
      BULL_VERSION: 'bull'
```

**Comment by SaschaVanEssen** [comment]
I am having the same issue. Did someone find a solution?
For me this problem only occurs when using a prefix.
docker-compose:
```
  sf-bullboard:
    container_name: sf-bullboard
    image: deadly0/bull-board
    restart: always
    environment:
      REDIS_HOST: sf-redis
      REDIS_PORT: 6379
      BULL_VERSION: bull
      BULL_PREFIX: sf-bull
    networks:
      - gcp_redis
    ports:
      - 8011:3000
```
And I am using the same BULL_PREFIX in Bull's Queue Options
